### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by PhillTV** [alex720/user-manager#11]
Can you Update User-Manager to Teamspeak version 3.3.2 Because i cant downgrade Teamspeak to 3.2.5 without 3.2.5installation.exe. If you have a 3.2.5 Version .exe or a Update, it would be very nice!

Thank you

**Comment by alex720** [comment]
I already done an Update for the newest Teamspeak Version. The plugin version 4.4.2.0 works on 3.3.2 and it was released on the 18 June.

**Comment by xStefan0** [comment]
The plugin version 4.4.2.0 is for Teamspeak Version 3.3.0+ and the plugin version 4.4.2 is for Teamspeak Version under 3.3.0 (3.2.5-)
