### ISSUE TITLE
Vorschlag eine kleine Änderung im Plugin für bessere Übersicht

### ISSUE THREAD

**Issue by xStefan0** [alex720/user-manager#14]
![Vorschlag Buddy](https://user-images.githubusercontent.com/48931862/71645614-1b8e6c00-2cdb-11ea-8d05-62b1b4f7c2eb.png)
![vorschlag blocked](https://user-images.githubusercontent.com/48931862/71645556-6b206800-2cda-11ea-8466-dc59de130a2f.png)
Wie wäre es wie auf den Screenshots unschwer zu erkennen, dass diese Ansicht übersichtlicher gemacht wird und man direkt erkennen kann ob derjenige Blocked oder Buddy im Plugin ist. Wenn der User im Plugin als Buddy markiert ist dann ist das Wort "Buddy" bei "User is Buddy" in Grün geschrieben und wenn der User im Plugin als blocked User markiert ist dann wird das "blocked" bei "UserID is blocked" oder ggf. falls nur der Nickname / Country blocked ist in Rot geschieben.

Freue mich über andere Vorschläge oder um eine Umsetzung sofern dies möglich ist.

Mfg

**Comment by alex720** [comment]
in der Version 4.4.5 umgesetzt
