### ISSUE TITLE
Fehler wird beim speichern der Einstellungen geworfen - nxtVentix

### ISSUE THREAD

**Issue by nxtVentix** [alex720/user-manager#5]
Hey,

Sobald man "Save & Apply" klickt wirft er dir immer den Fehler:
![dssd](https://user-images.githubusercontent.com/20678496/44310248-55efb580-a3d3-11e8-8754-b4beb529a93d.PNG)
Habe auch schon die Datenbank gelöscht, Plugin deaktiviert danach wieder aktiviert. 
Und auch neuinstalliert. 

Jedoch immer das gleiche.

MfG nxtVentix

**Comment by nxtVentix** [comment]
Steht doch im Bild?

Hatte auch schon mit Alex geredet jedoch immer das gleiche.
Hast du eine TeamSpeak-Adresse @Bluscream wo wir reden könnten?

LG

**Comment by Bluscream** [comment]
Da steht nirgendwo "Fehler" oder "Error" im bild

**Comment by nxtVentix** [comment]
![44310248-55efb580-a3d3-11e8-8754-b4beb529a93d](https://user-images.githubusercontent.com/20678496/44311488-c94ff200-a3e8-11e8-9c46-e1d6d135e3a8.PNG)

**Comment by Bluscream** [comment]
Oh nevermind hab nur die andere leiste geuckt

![grafik](https://user-images.githubusercontent.com/3318223/44312049-d87f7180-a3e1-11e8-9746-10401e92dec4.png)

Probiere mal die Datenbank unter `%appdata%\TS3Client\plugins\UserManager\UserManager.db` zu löschen.

**Comment by alex720** [comment]
@nxtVentix benutzt du die 4.3 oder die 4.3.0 ?

**Comment by alex720** [comment]
Könntest du den Ablauf der zu dem Fehler führt genauer beschreiben, ich kann diesen bei mir nicht reproduzieren.

**Comment by nxtVentix** [comment]
Neuste Version... 4.3.0

- https://youtu.be/CvK5xWglTz4

**Comment by nxtVentix** [comment]
Alles bugt rum, bei der aktuellesten TeamSpeak-Version mit dem Plugin!!!!!!!!!!!!
