### ISSUE TITLE
Cant Delete User

### ISSUE THREAD

**Issue by PhillTV** [alex720/user-manager#8]
After i added all my Buddies, it will Automaticly give ALL of them Channel operator. I cant Delete a Buddie or Block User from the List. How can i do that? I have more than 200 Friends

**Comment by alex720** [comment]
Currently there is no option to delete People with the contactlist. you need to rightclick them in the channeltree and remove them there. I will add a button in the next update

**Comment by alex720** [comment]
Fixed with the update 4.4.2
